FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux go build -o bin/server ./cmd/server

FROM alpine:latest
RUN apk --no-cache add tzdata
WORKDIR /app/
COPY --from=builder /app/bin/server .
COPY /configs/config.yaml /app/configs/config.yaml
CMD ["./server"]